
version: '3.8'
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: savedev
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cinema

    ports:
      - "5432:5432"
    volumes: 
      - postgres:/data/postgres
volumes:
  postgres:
    driver: local